name: seven_spot_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  google_sign_in: ^4.1.4
  firebase_auth: 0.15.4
  apple_sign_in: ^0.1.0
  device_info: ^0.4.1+4
  firebase_core: 0.4.4
  pull_to_refresh: ^1.5.8
  provider: ^3.1.0+1
  intl: ^0.16.1
  numberpicker: ^1.2.0
  encrypt: ^4.0.0
  pointycastle: ^1.0.2
  flutter_countdown_timer: ^1.1.0
  shimmer: ^1.1.1
  image_picker: ^0.6.6+5
  firebase_storage: ^3.1.6
  image_cropper: ^1.2.2
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/public.pem
    - assets/google_logo.png
    - assets/apple_logo.png
    - assets/ic_launcher.png
  fonts:
    - family: Lato
      fonts:
        - asset: assets/Lato-Light.ttf
          weight: 300
        - asset: assets/Lato-Regular.ttf
          weight: 400
        - asset: assets/Lato-Bold.ttf
          weight: 700
